### ISSUE TITLE
[Feature Request] Improve the theming of the Steam's Guides page

### ISSUE THREAD

**Issue by Patrxgt** [ShadowMonster99/simply-dark#28]
It would be nice if those elements could fit the overall theming a little more.
![obraz](https://github.com/user-attachments/assets/7de3c48b-0ee9-4d27-bac1-ab9fa2a7a9db)

**Comment by clawdius** [comment]
Hello, I've fixed the theming colors of the guide page, you can refer the new colors with the picture below:
![image](https://github.com/user-attachments/assets/a43b0b22-a377-40d5-a665-e370ea6d797a)

For the blue icon on the top, right below the "_popular category_", basically impossible to change its colors, since it is an icon, not a color.

**Comment by Patrxgt** [comment]
Thanks! As for the blue icons, I think it looks great that way.
